travis:
  secure:
    BINSTAR_TOKEN: QFOAy1xMWVsJAN9KplmDyxbdgYcafT26KNyh6r+kwKACK9qCnkMtIzUAVnrLqGZJGuK1uf/x4lo55tvPYvLV/xYxFgYb0vPCEKq1XUeq1QDESxmQ38Z0O9SPTV6Y16y/HFH2qj7N//GbphNxbeijFAi8k6ssmcTME2G1UYtPv7BhuJAvGgHgMLKro2DaIz5tCznjewlKN4VRHlq7hU5faSLolzxd8ndlMIecAJBO1uQzy/yuLyR5FgMHKCabNQwVPaV+qWS63HuVUMqXCMeEV7E2fV9G6gmSC+i6HP167wl43OsFEZSACKST7x/RP9jjf8l+Mv7//Ks7fzmGEIQeal4euwxP7FGZQ/igC1GLFrbWVebU2roi8EcIEyb929V9jUt+nFVGLXiKJiH8BuWjTg+9ztnTQJTqpULQtYsEBNFxq9oOdmt+n1CIL8y7HgQMdTHih5E1RjIrBVSq+81UZEaomgWiW+6xMFm5QJM6If5DH4d59w4S66rgy7qLhc68ZdJe5YT1Wl4Mvuqz609iSsQWKt7HpwEjCeBmuQu5yLzjH/uqtKwL50M1nCvsqZlkbZFVjJH3CE7gXB7w54P4KktTd2CLKMj1iwXzUY82/1Gw9yckQzXjTbQpiZWHIwHziEt669bmWYg+53wHn8Fl+k1uy9wtVXiE8wtkl53ET4g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
